### ISSUE TITLE
Track Number

### ISSUE THREAD

**Issue by BLoodConstructions** [tbouron/MMM-Sonos#6]
Hi,
is it possible to add the track number in front of the track. On which api or whatever is the module running. From what does ist get the data?

**Comment by Dennis-Rosenbaum** [comment]
@BLoodConstructions it uses the node-sonos library under the hood. You could see if the information is available in [their library](https://github.com/bencevans/node-sonos?tab=readme-ov-file#api)

**Comment by BLoodConstructions** [comment]
Ok. Solved it by myself.
